sudo: required
language: csharp

# Use latest images for building
group: travis_latest
os:
  - linux

dotnet: 2.1.300
script:  
  - ./build.sh --configuration "Release"  

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/abf03510b7719b383e2b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: never
