jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      git fetch --tags
      export COREHOST_TRACE=0
      export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      which dotnet
      dotnet --info
      dotnet tool install -g Cake.Tool --version 0.30.0
      export PATH="$PATH:$HOME/.dotnet/tools"
      dotnet cake build.cake -Configuration="Release" -Target="Linux"
      cd packages
      ./package-debian.sh
      cd ..

  - script: |
      cd AvalonStudio/AvalonStudioBuild
      dotnet publish -c Release -f netcoreapp2.2 -r linux-x64
      
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: packages/deb-out
     
- job: macOS
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: |
      git fetch --tags
      export COREHOST_TRACE=0
      export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      export DOTNET_CLI_TELEMETRY_OPTOUT=1
      which dotnet
      dotnet --info
      dotnet tool install -g Cake.Tool --version 0.30.0
      export PATH="$PATH:$HOME/.dotnet/tools"
      dotnet cake build.cake -Configuration="Release" -Target="OSX"
      cd packages
      ./package-osx.sh
      cd ..
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: packages/artifacts

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      git fetch --tags
      set COREHOST_TRACE=0
      set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
      set DOTNET_CLI_TELEMETRY_OPTOUT=1
      where dotnet
      dotnet --info
      dotnet tool install -g Cake.Tool --version 0.30.0
      set PATH=%PATH%;%USERPROFILE%\.dotnet\tools
      dotnet cake build.cake -Configuration="Release"
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: artifacts/zip/